name: ci

on:
  push:

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      
      - name: Build and push
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/nyok92/cyborgbackup:latest
            ghcr.io/nyok92/cyborgbackup:1.0.0

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1.6.0
        with:
          artifacts_directory: debian_output
      - uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: debian_output
